### ISSUE TITLE
Missing server?

### ISSUE THREAD

**Issue by mhkeller** [jwilber/mosaic_play#1]
When  I try to run this I get a websocket error saying there was no connection to port 3000. I'm guessing the vgplot coordinator is looking for a running duckdb server on that port. 

Looks like you need to add something like this in the `onMount`

```js
const wasm = await vg.wasmConnector();
vg.coordinator().databaseConnector(wasm);
```

That being said, I still run into these error once that is fixed: ![Screenshot 2023-09-20 at 3 44 53 PM](https://github.com/jwilber/mosaic_play/assets/498744/1a7415a8-5cdc-4ece-95ef-055a3b70a7d7)

**Comment by jwilber** [comment]
whoops! Pushed in a hurry for someone on twitter, totally left that out. Added + updated readme instructions :)

**Comment by mhkeller** [comment]
Ah neat thanks! Got it working and also these duckdb helper files are really useful. I have been looking for the correct pattern to write arrow buffers for [a while](https://github.com/apache/arrow/issues/35041) [now](https://github.com/duckdb/duckdb/discussions/7008) and [this](https://github.com/jwilber/mosaic_play/blob/main/src/lib/duckdb/bin/to-arrow.js) looks like a very straightforward technique. Thanks!

**Comment by mhkeller** [comment]
btw i also had to install `ws` and i dont have nodemon installed globally so i added that to the package.json as well.

**Comment by jwilber** [comment]
ah, ty for the heads up! will add those in
